### ISSUE TITLE
Log4Net file is not being created

### ISSUE THREAD

**Issue by momer79** [CarmonColvin/DemoWebApiUnityLog4Net#1]
i can't find any file with name DemoWebApiUnityLog4Net.log on my machine, it looks like log file is not being created.

**Comment by momer79** [comment]
After updating Global.asax file its now working.

//logger.Info(@"Application started");
logger.Info("Application started");

**Comment by CarmonColvin** [comment]
I know this is old but... Was that line commented out when you cloned this repo?
